
mcp.model.investigator=O3
mcp.model.planner=GPT54
mcp.model.code.generator=GPT52CODEX
mcp.model.code.auditor=CLAUDESONNET46
mcp.model.summarizer=GPT54MINI	

#################
#apenas para informacoa abaixo nao funciona por enquanto de verdade
mcp.creativity.investigator=0.10
mcp.creativity.planner=0.10
mcp.creativity.code.generator=0.00
mcp.creativity.code.auditor=0.00
mcp.creativity.summarizer=0.00