source.. = src/main/java/
output.. = bin/
# Data: 14-05-2026 17:51
# O espacamento interno foi removido para restabelecer o empacotamento dos diretorios
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               lib/gson-2.14.0.jar,\
               lib/vineflower-1.12.0.jar,\
               lib/org.eclipse.jgit-7.4.jar,\
               lib/slf4j-api-2.0.17.jar, \
               lib/slf4j-simple-2.0.17.jar

